spring:
  application:
    name: taskmanager

  datasource:
    url: jdbc:mysql://${DATABASE_URL:127.0.0.1}:${DATABASE_PORT:3306}/${DATABASE_NAME:taskmanager}?useUnicode=yes&characterEncoding=UTF-8
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true

  security:
    developer-password: ${DEVELOPER_PASSWORD:$2a$12$xZf87ptn/OKSrWaew/pWAurv1g0PpHwiWB21UuNZ/6kcAb.eHIyoq}

